trigger:
  branches:
    include:
      - main
      - master

pool:
  vmImage: Lab4.2

stages:
  - stage: Build
    displayName: "Build Stage"
    jobs:
      - job: BuildJob
        displayName: "Build Job"
        steps:
          - task: UseJavaVersion@1
            inputs:
              versionSpec: "11" # Use Java 11 or the version you need for your backend

          - task: Gradle@2
            displayName: "Build Java Backend"
            inputs:
              workingDirectory: "server-COMP303" # Change to your backend directory
              tasks: "build"

          - task: NodeTool@0
            inputs:
              versionSpec: "12.x"
            displayName: "Install Node.js"

          - script: |
              cd client-COMP303
              npm install
              npm run dev
            displayName: "Build Frontend"
            workingDirectory: "$(System.DefaultWorkingDirectory)" # Ensure correct working directory

          - task: SonarQubePrepare@4
            inputs:
              SonarQube: "SonarQubeConnection"
              scannerMode: "CLI"
              configMode: "manual"
              cliProjectKey: "your_project_key"
              cliSources: "server-COMP303/src" # Update source path for backend
              cliTests: "server-COMP303/src/test" # Update test path for backend

          - task: SonarQubeAnalyze@4
            displayName: "Run SonarQube Analysis"
            inputs:
              projectName: "your_project_name"
              projectKey: "your_project_key"
              extraProperties: |
                # Additional properties for SonarQube analysis, if any

          - task: SonarQubePublish@4
            inputs:
              pollingTimeoutSec: "300"
