trigger:
  branches:
    include:
      - main
      - master

pool:
  vmImage: Lab4.2

stages:
  - stage: Build
    displayName: "Build Stage"
    jobs:
      - job: BuildJob
        displayName: "Build Job"
        steps:
          - task: UseJavaVersion@1
            inputs:
              versionSpec: "11" # Use Java 11 or the version you need for your backend

          - task: NodeTool@0
            inputs:
              versionSpec: "12.x"
            displayName: "Install Node.js"

          - script: |
              cd client-COMP303
              npm install
              npm run dev
            displayName: "Build Frontend"
            workingDirectory: "$(System.DefaultWorkingDirectory)" # Ensure correct working directory

          - task: SonarQubePrepare@4
            inputs:
              SonarQube: "SonarQubeConnection"
              scannerMode: "CLI"
              configMode: "manual"
              cliProjectKey: "your_project_key"
              cliSources: "server-COMP303/src" # Update source path for backend
              cliTests: "server-COMP303/src/test" # Update test path for backend

          - task: SonarQubeAnalyze@4
            displayName: "Run SonarQube Analysis"
            inputs:
              projectName: "your_project_name"
              projectKey: "your_project_key"
              extraProperties: |
                # Additional properties for SonarQube analysis, if any

          - task: SonarQubePublish@4
            inputs:
              pollingTimeoutSec: "300"

  - stage: DeployDevEnv
    displayName: "Deploy to Dev Environment"
    jobs:
      - job: DeployDevJob
        displayName: "Deploy to Dev Job"
        steps:
          - script: echo "Mock deployment to Dev environment"
            displayName: "Mock Deployment to Dev"

  - stage: DeployQATEnv
    displayName: "Deploy to QAT Environment"
    jobs:
      - job: DeployQATJob
        displayName: "Deploy to QAT Job"
        steps:
          - script: echo "Mock deployment to QAT environment"
            displayName: "Mock Deployment to QAT"

  - stage: DeployStagingEnv
    displayName: "Deploy to Staging Environment"
    jobs:
      - job: DeployStagingJob
        displayName: "Deploy to Staging Job"
        steps:
          - script: echo "Mock deployment to Staging environment"
            displayName: "Mock Deployment to Staging"

  - stage: DeployProdEnv
    displayName: "Deploy to Production Environment"
    jobs:
      - job: DeployProdJob
        displayName: "Deploy to Production Job"
        steps:
          - script: echo "Mock deployment to Production environment"
            displayName: "Mock Deployment to Production"
